export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as AddProduct } from './AddProduct';
export { default as CategorySelect } from './CategorySelect';
export { default as ProductInput } from './ProductInput';
export { default as ProductList } from './ProductList';
export { default as CreateProduct } from './CreateProduct';
export { default as SubmitProducts } from './SubmitProducts';
export { default as TotalItems } from './TotalItems';
